version: "3.5"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - MIEL_Board_DB
    environment:
      MYSQL_DATABASE: board
      MYSQL_USER: miel
      MYSQL_PASSWORD: miel
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      TZ: Asia/Seoul
    volumes:
      - ./data/db:/var/lib/mysql
      - ./config/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    networks:
      - MIEL_Board_DB
    ports:
      - 10240:80
    environment:
      PMA_HOST: db
      PMA_USER: miel
      PMA_PASSWORD: miel
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - 3000:80
    networks:
      - MIEL_Board_DB
    volumes:
      - ./config/proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: always
  express:
    build:
      context: ./src
    container_name: express
    expose:
      - "3000"
    networks:
      - MIEL_Board_DB
    volumes:
      - ./src:/source
      - /source/node_modules
    restart: always

networks:
  MIEL_Board_DB:
    external:
      name: MIEL_Board_DB
  MIEL_Board_API:
    external:
      name: MIEL_Board_API
